/* Loader de compatibilidade — sincronização cloud original + fallback seguro do Plano de Carreira. */
(function(){
  'use strict';
  const ORIGINAL_SYNC='https://raw.githubusercontent.com/juniorsousa-oss/gestao-almoxarifado/85378684a950f306e1880dd3df6cb8fc7ac0178c/supabase-sync.js';
  const CAREER='./plano-carreira-v2.js';
  let fallbackLoading=false;
  function loadScript(src,onload,onerror){const s=document.createElement('script');s.src=src;s.async=false;s.onload=function(){if(onload)onload();};s.onerror=function(){if(onerror)onerror(src);};document.head.appendChild(s);}
  function normalize(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim();}
  function ensureCareerNav(){const nav=document.querySelector('.nav');if(!nav)return false;let btn=document.getElementById('navCarreira');if(!btn){btn=document.createElement('button');btn.id='navCarreira';btn.type='button';btn.innerHTML='PLANO DE CARREIRA';const teamBtn=Array.from(nav.querySelectorAll('button')).find(b=>normalize(b.textContent).includes('GESTAO DE EQUIPES'));if(teamBtn)teamBtn.insertAdjacentElement('afterend',btn);else nav.appendChild(btn);}btn.onclick=function(){if(typeof window.openCareerModule==='function'){window.openCareerModule();return;}if(fallbackLoading)return;fallbackLoading=true;loadScript(CAREER+'?fallback='+Date.now(),function(){fallbackLoading=false;if(typeof window.openCareerModule==='function')window.openCareerModule();else if(typeof window.renderCareerModule==='function')window.renderCareerModule();else alert('Não foi possível inicializar o Plano de Carreira.');},function(){fallbackLoading=false;alert('Não foi possível carregar o Plano de Carreira.');});};return true;}
  function installProfessionalSidebar(){const old=document.getElementById('professional-sidebar-v2');if(old)old.remove();const style=document.createElement('style');style.id='professional-sidebar-final';style.textContent=`
.sidebar{width:252px!important;position:fixed!important;inset:0 auto 0 0!important;padding:0 12px 18px!important;background:#090c0b!important;border-right:1px solid #252b28!important;box-shadow:none!important;z-index:20!important}.brand{height:108px!important;margin:0 0 10px!important;padding:10px 10px 16px!important;display:flex!important;align-items:center!important;justify-content:center!important;border-bottom:1px solid #1e2522!important}.brand img{display:block!important;width:auto!important;max-width:170px!important;max-height:68px!important;object-fit:contain!important}.nav{display:flex!important;flex-direction:column!important;gap:3px!important;width:100%!important;margin:0!important;padding:0!important}.nav button,.nav button#navCarreira{width:100%!important;height:54px!important;min-height:54px!important;margin:0!important;padding:0 12px!important;display:grid!important;grid-template-columns:34px minmax(0,1fr)!important;align-items:center!important;column-gap:8px!important;border:1px solid transparent!important;border-radius:11px!important;background:transparent!important;color:#dfe4e1!important;text-align:left!important;font-family:Inter,Segoe UI,Arial,sans-serif!important;font-size:13px!important;font-weight:800!important;line-height:1!important;white-space:nowrap!important;overflow:hidden!important;box-shadow:none!important;transform:none!important}.nav button:hover{background:#121715!important;color:#fff!important}.nav button.active{background:#ffd43b!important;color:#111!important;border-color:#ffd43b!important;border-radius:11px!important}.nav button .menu-icon{width:30px!important;height:30px!important;display:grid!important;place-items:center!important;color:#c9d0cc!important}.nav button.active .menu-icon{color:#111!important}.nav button .menu-icon svg{width:20px!important;height:20px!important;display:block!important;stroke:currentColor!important;fill:none!important;stroke-width:1.8!important;stroke-linecap:round!important;stroke-linejoin:round!important}.nav button .menu-label{min-width:0!important;display:block!important;overflow:hidden!important;text-overflow:ellipsis!important;white-space:nowrap!important}.sidebar-footer{margin-top:auto!important;padding:12px 8px 2px!important}.main{margin-left:252px!important;width:calc(100% - 252px)!important}@media(max-width:1050px){.sidebar{width:230px!important}.main{margin-left:230px!important;width:calc(100% - 230px)!important}}@media(max-width:700px){.sidebar{position:static!important;width:100%!important;height:auto!important;padding:12px!important}.brand{height:88px!important;margin-bottom:8px!important}.nav{flex-direction:column!important;overflow:visible!important}.nav button{height:50px!important;min-height:50px!important}.main{margin-left:0!important;width:100%!important}}`;
    document.head.appendChild(style);
    const icons={'DASHBOARD':'<svg viewBox="0 0 24 24"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></svg>','ALIMENTAR INDICADORES':'<svg viewBox="0 0 24 24"><path d="M5 19 19 5"/><path d="m14 5 5 5"/><path d="M4 20h4"/></svg>','HISTÓRICO':'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="8.5"/><path d="M12 7v5l3.5 2"/></svg>','GESTÃO DE EQUIPES':'<svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><path d="M3.5 20c.5-3.5 2.5-5.5 5.5-5.5s5 2 5.5 5.5"/><path d="M15 6a3 3 0 0 1 0 5.8M17 15c2 .5 3.2 2.1 3.5 4"/></svg>','PLANO DE CARREIRA':'<svg viewBox="0 0 24 24"><path d="M12 20V4"/><path d="m6 10 6-6 6 6"/></svg>','CONFIGURAÇÕES':'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/></svg>'};
    function labelOf(btn){return normalize(String(btn.textContent||'').replace(/[\u{1F300}-\u{1FAFF}\u2600-\u27BF]/gu,'').replace(/\s+/g,' '));}
    function formatButton(btn){if(!btn)return;const label=labelOf(btn);const key=Object.keys(icons).find(k=>label===normalize(k)||label.includes(normalize(k)));if(!key)return;btn.setAttribute('aria-label',key);btn.innerHTML='<span class="menu-icon" aria-hidden="true">'+icons[key]+'</span><span class="menu-label">'+key+'</span>';}
    function apply(){const nav=document.querySelector('.nav');if(!nav)return false;ensureCareerNav();nav.querySelectorAll('button').forEach(formatButton);return true;}apply();[50,200,500,1000,2000,3500].forEach(ms=>setTimeout(apply,ms));}
  function boot(){ensureCareerNav();installProfessionalSidebar();setTimeout(ensureCareerNav,250);setTimeout(ensureCareerNav,1000);setTimeout(ensureCareerNav,2500);}
  loadScript(ORIGINAL_SYNC,function(){console.info('[BOOT] Sincronização cloud original carregada.');},function(src){console.error('[BOOT] Falha na sincronização cloud original:',src);});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();